// <auto-generated />
namespace DO_AN_APS_DOC_NET_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddColIsPayedInModelBill : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddColIsPayedInModelBill));
        
        string IMigrationMetadata.Id
        {
            get { return "202107260730016_AddColIsPayedInModelBill"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
